---
stages:
  - build

build:
  stage: build
  image: node:16
  tags:
    - shared_build
  script:
    - cd client
    - npm ci
    - npm run build
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - dist/*
    expire_in: "1 days"
