---
stages:
  - build
  - deploy

build_front:
  stage: build
  image: node:16
  tags:
    - shared_build
  script:
    - cd client
    - npm ci
    - npm run build
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - client/dist/
    expire_in: "1 days"

build_server:
  stage: build
  image: docker:latest
  tags:
    - shared_build
  before_script:
    - docker login ${DOCKER_REGISTRY}/${CI_PROJECT_NAMESPACE} -u $REG_USER -p $REG_TOKEN
  script:
    - cd server
    - docker build -t ${DOCKER_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_SHA} -t ${DOCKER_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:latest .
    - docker push ${DOCKER_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_SHA}
    - docker push ${DOCKER_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:latest
