---
stages:
  - build
  - deploy

build_front:
  stage: build
  image: node:16
  tags:
    - shared_build
  script:
    - cd client
    - npm ci
    - npm run build
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - client/dist/
    expire_in: "1 days"

build_server:
  stage: build
  image: docker:latest
  tags:
    - shared_build
  before_script:
    - docker login ${DOCKER_REGISTRY}/${CI_PROJECT_NAMESPACE} -u $REG_USER -p $REG_TOKEN
  script:
    - cd server
    - docker build -t ${DOCKER_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_SHA} -t ${DOCKER_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:latest .
    - docker push ${DOCKER_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${CI_COMMIT_SHA}
    - docker push ${DOCKER_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:latest

deploy_server:
  stage: deploy
  image: docker/compose:latest
  tags:
    - outplay
  before_script:
    - docker login ${DOCKER_REGISTRY}/${CI_PROJECT_NAMESPACE} -u $REG_USER -p $REG_TOKEN
  script:
    - cd server
    - docker-compose up -d --force-recreate
  needs:
    - job: build_server

deploy_front:
  stage: deploy
  tags:
    - outplay-onhost
  script:
    - sudo cp -r client/dist/* /home/minima/.minima_102_9121/0.103/mds/web/0x191268E13E87180A6EF20BF40AC6480E/
    - sudo chown -R minima:minima /home/minima/.minima_102_9121/0.103/mds/web/0x191268E13E87180A6EF20BF40AC6480E
  dependencies:
    - build_front
  needs:
    - job: build_front
