---
stages:
  - build

build:
  stage: build
  image: node:16
  tags:
    - shared_build
  script:
    - cd client
    - npm ci
    - npm run build
    #- tar -cvf artifacts.tar.gz dist/
    #- ls -la
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      #  - artifacts.tar.gz
      - client/dist/
    expire_in: "1 days"
