version: '3.5'

services:
  db:
    container_name: postgres-nodejs-learning
    image: 'postgres'
    restart: always
    ports:
      - '1234:5432'
    environment:
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_USER=${TYPEORM_USER}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - postgres

  outplay-backend:
    container_name: outplay-backend
    image: gitlab.vercloud.ru:5050/lucid/outplay/outplay:6c9ddfa1215699f529db1058ec0ceddb06555b8d
    restart: unless-stopped
    networks:
      - backend

volumes:
  data:


networks:
  postgres:
    name: outplay-net
  backend:
    name: outplay-net
